import type { Deal, DealCategory, PriceTier, Profile } from "@/types/birge";

export const formatKzt = (value: number) =>
  new Intl.NumberFormat("ru-KZ", {
    maximumFractionDigits: 0,
  }).format(value) + " ₸";

const categoryLabels: Record<DealCategory, string> = {
  electronics: "электроника",
  home: "дом",
  beauty: "красота",
  sport: "спорт",
  kids: "детям",
  auto: "авто",
  fashion: "одежда",
};

export const categoryNav: { label: string; value: DealCategory | "all"; href: string }[] = [
  { label: "Deals", value: "all", href: "/#deals" },
  { label: "Electronics", value: "electronics", href: "/?category=electronics#deals" },
  { label: "Home", value: "home", href: "/?category=home#deals" },
  { label: "Beauty", value: "beauty", href: "/?category=beauty#deals" },
  { label: "Sport", value: "sport", href: "/?category=sport#deals" },
  { label: "Kids", value: "kids", href: "/?category=kids#deals" },
  { label: "Auto", value: "auto", href: "/?category=auto#deals" },
];

const escrowNotes = [
  "Деньги удерживаются в эскроу",
  "Если группа не собралась — авто-возврат",
  "После сбора — заказ уходит в карго-консолидацию",
];

function tiers(currentTarget: number, discount: number): PriceTier[] {
  if (currentTarget <= 10) {
    return [
      { people: 5, discount: 12, status: "unlocked" },
      { people: 10, discount, status: "current" },
      { people: 25, discount: Math.min(45, discount + 8), status: "locked" },
    ];
  }

  if (currentTarget >= 50) {
    return [
      { people: 20, discount: 18, status: "unlocked" },
      { people: 50, discount, status: "current" },
      { people: 100, discount: Math.min(46, discount + 10), status: "locked" },
    ];
  }

  return [
    { people: 10, discount: 15, status: "unlocked" },
    { people: 20, discount, status: "current" },
    { people: 50, discount: Math.min(42, discount + 9), status: "locked" },
  ];
}

function recommendationSignals(category: DealCategory, city: Deal["city"], finalPrice: number, participants: number, target: number) {
  const interestMatch = ["electronics", "home", "beauty"].includes(category) ? 1 : category === "kids" ? 0.75 : 0.55;
  const budgetFit = finalPrice <= 50000 ? 1 : finalPrice <= 90000 ? 0.75 : 0.45;
  const cityMatch = city === "Алматы" ? 1 : 0.55;
  const momentum = Math.min(1, participants / target);
  const score = Number((0.4 * interestMatch + 0.2 * budgetFit + 0.2 * cityMatch + 0.2 * momentum).toFixed(2));
  return { interestMatch, budgetFit, cityMatch, momentum: Number(momentum.toFixed(2)), score };
}

type DealSeed = Omit<Deal, "categoryLabel" | "visual" | "visualTone" | "image" | "image480" | "recommendationSignals" | "tiers" | "escrowNotes" | "href"> & {
  tone: string;
};

/** Explicit per-deal visual: exact local photo only when semantically correct. */
const dealVisualMap: Record<string, string> = {
  "wireless-headphones": "headphones.jpg",
  "mini-projector": "mini-projector.jpg",
  "smartwatch-gps": "smartwatch.jpg",
  "power-bank": "power-bank.jpg",
  "robot-vacuum": "robot-vacuum.jpg",
  "kitchen-organizer": "kitchen-organizer.jpg",
  "portable-blender": "portable-blender.jpg",
  "air-humidifier": "humidifier.jpg",
  "korean-skincare": "skincare-set.jpg",
  "hair-styler": "hair-styler.jpg",
  "led-beauty-mirror": "led-mirror.jpg",
  "makeup-organizer": "makeup-organizer.jpg",
  "basketball-kit": "basketball-training-kit.jpg",
  "resistance-bands": "resistance-bands.jpg",
  "gym-shaker-straps": "gym-shaker-straps.jpg",
  "running-belt": "running-belt.jpg",
  "kids-tablet": "kids-tablet.jpg",
  "baby-monitor": "baby-monitor.jpg",
  "kids-backpack": "kids-backpack.jpg",
  "toy-constructor": "toy-constructor.jpg",
  "tire-inflator": "tire-inflator.jpg",
  "car-vacuum": "car-vacuum.jpg",
  "phone-holder": "phone-holder.jpg",
  "dash-cam": "dash-cam.jpg",
  "travel-jacket": "urban-jacket.jpg",
  "summer-shirt": "summer-shirt.jpg",
  "city-sneakers": "sneakers.jpg",
  "summer-cap": "cap.jpg",
};

function deal(seed: DealSeed): Deal {
  const imageFile = dealVisualMap[seed.id];
  if (!imageFile) {
    throw new Error(`Missing product photo mapping for deal: ${seed.id}`);
  }
  const imagePath = `/images/products/${imageFile}`;
  return {
    ...seed,
    image: imagePath,
    image480: imagePath,
    categoryLabel: categoryLabels[seed.category],
    visual: "photo",
    visualTone: seed.tone,
    recommendationSignals: recommendationSignals(seed.category, seed.city, seed.finalPrice, seed.participants, seed.target),
    tiers: tiers(seed.target, seed.discount),
    escrowNotes,
    href: `/deal/${seed.id}`,
  };
}

export const deals: Deal[] = [
  deal({
    id: "wireless-headphones",
    category: "electronics",
    titleRu: "Беспроводные наушники с шумоподавлением",
    titleKz: "Шуды басатын сымсыз құлаққап",
    description: "Компактные ANC-наушники для города, работы и перелетов.",
    tone: "audio",
    city: "Алматы",
    source: "AliExpress",
    retailPrice: 25200,
    groupPrice: 15900,
    cargoCost: 1800,
    finalPrice: 17900,
    discount: 29,
    participants: 14,
    target: 20,
    countdown: "02:18:44",
    recommendation: "электроника · Алматы · в бюджете",
    savingsAmount: 7300,
  }),
  deal({
    id: "mini-projector",
    category: "electronics",
    titleRu: "Мини-проектор для дома",
    titleKz: "Үйге арналған шағын проектор",
    description: "Портативный проектор для кино, презентаций и детской комнаты.",
    tone: "projector",
    city: "Астана",
    source: "Temu mock",
    retailPrice: 84900,
    groupPrice: 56900,
    cargoCost: 3600,
    finalPrice: 60500,
    discount: 29,
    participants: 11,
    target: 20,
    countdown: "04:35:18",
    recommendation: "электроника · высокий спрос · tier 20",
    savingsAmount: 24400,
  }),
  deal({
    id: "smartwatch-gps",
    category: "electronics",
    titleRu: "Smartwatch с GPS и пульсометром",
    titleKz: "GPS және пульс өлшегіші бар smartwatch",
    description: "Часы для спорта, уведомлений и контроля здоровья.",
    tone: "watch",
    city: "Астана",
    source: "AliExpress",
    retailPrice: 68900,
    groupPrice: 46200,
    cargoCost: 2100,
    finalPrice: 48300,
    discount: 30,
    participants: 9,
    target: 10,
    countdown: "01:12:09",
    recommendation: "электроника · Астана · почти собрались",
    savingsAmount: 20600,
  }),
  deal({
    id: "power-bank",
    category: "electronics",
    titleRu: "Power bank 20 000 mAh",
    titleKz: "20 000 mAh power bank",
    description: "Быстрая зарядка для смартфона, планшета и поездок.",
    tone: "battery",
    city: "Алматы",
    source: "1688",
    retailPrice: 21900,
    groupPrice: 13900,
    cargoCost: 1200,
    finalPrice: 15100,
    discount: 31,
    participants: 43,
    target: 50,
    countdown: "00:41:22",
    recommendation: "электроника · Алматы · в бюджете",
    savingsAmount: 6800,
  }),
  deal({
    id: "robot-vacuum",
    category: "home",
    titleRu: "Робот-пылесос для квартиры",
    titleKz: "Пәтерге арналған робот шаңсорғыш",
    description: "Робот с влажной уборкой и картой помещения.",
    tone: "vacuum",
    city: "Астана",
    source: "1688",
    retailPrice: 139900,
    groupPrice: 91900,
    cargoCost: 6400,
    finalPrice: 98300,
    discount: 30,
    participants: 31,
    target: 50,
    countdown: "05:42:10",
    recommendation: "дом · Астана · высокий спрос",
    savingsAmount: 41600,
  }),
  deal({
    id: "kitchen-organizer",
    category: "home",
    titleRu: "Набор кухонных органайзеров",
    titleKz: "Ас үй органайзерлер жинағы",
    description: "Модульные контейнеры для круп, специй и хранения.",
    tone: "organizer",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 31900,
    groupPrice: 20500,
    cargoCost: 1800,
    finalPrice: 22300,
    discount: 30,
    participants: 18,
    target: 20,
    countdown: "03:18:52",
    recommendation: "кухня · Алматы · в бюджете",
    savingsAmount: 9600,
  }),
  deal({
    id: "portable-blender",
    category: "home",
    titleRu: "Портативный блендер",
    titleKz: "Портативті блендер",
    description: "USB-блендер для смузи, офиса и тренировок.",
    tone: "blender",
    city: "Алматы",
    source: "AliExpress",
    retailPrice: 27900,
    groupPrice: 17800,
    cargoCost: 1700,
    finalPrice: 19500,
    discount: 30,
    participants: 12,
    target: 20,
    countdown: "08:04:31",
    recommendation: "дом · Алматы · семейный бюджет",
    savingsAmount: 8400,
  }),
  deal({
    id: "air-humidifier",
    category: "home",
    titleRu: "Увлажнитель воздуха",
    titleKz: "Ауа ылғалдандырғыш",
    description: "Тихий увлажнитель для спальни и детской.",
    tone: "humidifier",
    city: "Астана",
    source: "1688",
    retailPrice: 36900,
    groupPrice: 23900,
    cargoCost: 2100,
    finalPrice: 26000,
    discount: 30,
    participants: 24,
    target: 30,
    countdown: "06:51:03",
    recommendation: "дом · Астана · сезонный спрос",
    savingsAmount: 10900,
  }),
  deal({
    id: "korean-skincare",
    category: "beauty",
    titleRu: "Корейский набор ухода за кожей",
    titleKz: "Кореялық тері күтімі жинағы",
    description: "Тонер, сыворотка, крем и SPF для ежедневного ухода.",
    tone: "skincare",
    city: "Алматы",
    source: "Amazon",
    retailPrice: 48600,
    groupPrice: 32900,
    cargoCost: 2400,
    finalPrice: 35300,
    discount: 27,
    participants: 18,
    target: 20,
    countdown: "00:56:32",
    recommendation: "красота · Алматы · почти собрались",
    savingsAmount: 13300,
  }),
  deal({
    id: "hair-styler",
    category: "beauty",
    titleRu: "Мультистайлер для волос",
    titleKz: "Шашқа арналған мультистайлер",
    description: "Насадки для укладки, сушки и прикорневого объема.",
    tone: "styler",
    city: "Астана",
    source: "AliExpress",
    retailPrice: 79900,
    groupPrice: 52900,
    cargoCost: 3300,
    finalPrice: 56200,
    discount: 30,
    participants: 13,
    target: 20,
    countdown: "04:09:12",
    recommendation: "красота · высокий чек · tier 20",
    savingsAmount: 23700,
  }),
  deal({
    id: "led-beauty-mirror",
    category: "beauty",
    titleRu: "LED-зеркало для макияжа",
    titleKz: "Макияжға арналған LED айна",
    description: "Три режима света, компактная подставка и USB-зарядка.",
    tone: "mirror",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 24900,
    groupPrice: 15900,
    cargoCost: 1400,
    finalPrice: 17300,
    discount: 31,
    participants: 7,
    target: 10,
    countdown: "02:44:10",
    recommendation: "красота · Алматы · в бюджете",
    savingsAmount: 7600,
  }),
  deal({
    id: "makeup-organizer",
    category: "beauty",
    titleRu: "Органайзер для косметики",
    titleKz: "Косметикаға арналған органайзер",
    description: "Прозрачные ящики для ухода, кистей и декоративной косметики.",
    tone: "beautybox",
    city: "Алматы",
    source: "1688",
    retailPrice: 18900,
    groupPrice: 11900,
    cargoCost: 1200,
    finalPrice: 13100,
    discount: 31,
    participants: 38,
    target: 50,
    countdown: "11:17:45",
    recommendation: "красота · Алматы · дешевле вместе",
    savingsAmount: 5800,
  }),
  deal({
    id: "basketball-kit",
    category: "sport",
    titleRu: "Баскетбольный тренировочный набор",
    titleKz: "Баскетбол жаттығу жинағы",
    description: "Мяч, конусы, эспандер и сумка для тренировок.",
    tone: "basketball",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 38900,
    groupPrice: 24900,
    cargoCost: 2200,
    finalPrice: 27100,
    discount: 30,
    participants: 15,
    target: 20,
    countdown: "05:01:29",
    recommendation: "спорт · Алматы · командная покупка",
    savingsAmount: 11800,
  }),
  deal({
    id: "resistance-bands",
    category: "sport",
    titleRu: "Набор эспандеров",
    titleKz: "Эспандерлер жинағы",
    description: "Пять уровней нагрузки для дома, зала и реабилитации.",
    tone: "bands",
    city: "Астана",
    source: "AliExpress",
    retailPrice: 16900,
    groupPrice: 9900,
    cargoCost: 900,
    finalPrice: 10800,
    discount: 36,
    participants: 8,
    target: 10,
    countdown: "01:36:40",
    recommendation: "спорт · Астана · почти собрались",
    savingsAmount: 6100,
  }),
  deal({
    id: "gym-shaker-straps",
    category: "sport",
    titleRu: "Шейкер и кистевые лямки",
    titleKz: "Шейкер және білезік баулары",
    description: "Комплект для силовых тренировок и протеиновых коктейлей.",
    tone: "shaker",
    city: "Алматы",
    source: "1688",
    retailPrice: 14900,
    groupPrice: 9100,
    cargoCost: 800,
    finalPrice: 9900,
    discount: 34,
    participants: 27,
    target: 30,
    countdown: "00:52:09",
    recommendation: "спорт · Алматы · в бюджете",
    savingsAmount: 5000,
  }),
  deal({
    id: "running-belt",
    category: "sport",
    titleRu: "Пояс для бега",
    titleKz: "Жүгіруге арналған белдік",
    description: "Влагозащита, отделение для телефона и ключей.",
    tone: "running",
    city: "Алматы",
    source: "Amazon",
    retailPrice: 12900,
    groupPrice: 7900,
    cargoCost: 700,
    finalPrice: 8600,
    discount: 33,
    participants: 21,
    target: 30,
    countdown: "09:28:31",
    recommendation: "спорт · Алматы · городские пробежки",
    savingsAmount: 4300,
  }),
  deal({
    id: "kids-tablet",
    category: "kids",
    titleRu: "Детский обучающий планшет",
    titleKz: "Балаларға арналған оқу планшеті",
    description: "Обучающие игры, родительский режим и ударопрочный чехол.",
    tone: "tablet",
    city: "Алматы",
    source: "1688",
    retailPrice: 52900,
    groupPrice: 34900,
    cargoCost: 2300,
    finalPrice: 37200,
    discount: 30,
    participants: 22,
    target: 30,
    countdown: "07:04:55",
    recommendation: "детям · Алматы · семейный бюджет",
    savingsAmount: 15700,
  }),
  deal({
    id: "baby-monitor",
    category: "kids",
    titleRu: "Видеоняня с ночным режимом",
    titleKz: "Түнгі режимі бар бейнебақылау",
    description: "Камера, монитор, двусторонняя связь и датчик шума.",
    tone: "monitor",
    city: "Астана",
    source: "AliExpress",
    retailPrice: 64900,
    groupPrice: 42900,
    cargoCost: 2800,
    finalPrice: 45700,
    discount: 30,
    participants: 10,
    target: 20,
    countdown: "12:15:02",
    recommendation: "детям · безопасность · SIM-проверено",
    savingsAmount: 19200,
  }),
  deal({
    id: "kids-backpack",
    category: "kids",
    titleRu: "Детский городской рюкзак",
    titleKz: "Балаларға арналған қалалық рюкзак",
    description: "Легкий рюкзак с ортопедической спинкой.",
    tone: "backpack",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 22900,
    groupPrice: 14900,
    cargoCost: 1300,
    finalPrice: 16200,
    discount: 29,
    participants: 33,
    target: 50,
    countdown: "02:25:46",
    recommendation: "детям · Алматы · школьный сезон",
    savingsAmount: 6700,
  }),
  deal({
    id: "toy-constructor",
    category: "kids",
    titleRu: "Конструктор STEM",
    titleKz: "STEM конструкторы",
    description: "Набор деталей для инженерных игр и развития логики.",
    tone: "constructor",
    city: "Астана",
    source: "1688",
    retailPrice: 34900,
    groupPrice: 22900,
    cargoCost: 1900,
    finalPrice: 24800,
    discount: 29,
    participants: 19,
    target: 20,
    countdown: "00:39:18",
    recommendation: "детям · Астана · почти закрыта",
    savingsAmount: 10100,
  }),
  deal({
    id: "tire-inflator",
    category: "auto",
    titleRu: "Портативный компрессор для шин",
    titleKz: "Шиналарға арналған портативті компрессор",
    description: "Цифровой манометр, автостоп и питание от USB-C.",
    tone: "inflator",
    city: "Алматы",
    source: "AliExpress",
    retailPrice: 43900,
    groupPrice: 27900,
    cargoCost: 1900,
    finalPrice: 29800,
    discount: 32,
    participants: 16,
    target: 20,
    countdown: "03:31:18",
    recommendation: "авто · Алматы · SIM-проверено",
    savingsAmount: 14100,
  }),
  deal({
    id: "car-vacuum",
    category: "auto",
    titleRu: "Автомобильный пылесос",
    titleKz: "Автокөлік шаңсорғышы",
    description: "Беспроводной пылесос для салона с HEPA-фильтром.",
    tone: "carvac",
    city: "Астана",
    source: "1688",
    retailPrice: 36900,
    groupPrice: 23900,
    cargoCost: 1800,
    finalPrice: 25700,
    discount: 30,
    participants: 28,
    target: 30,
    countdown: "01:08:11",
    recommendation: "авто · Астана · почти собрались",
    savingsAmount: 11200,
  }),
  deal({
    id: "phone-holder",
    category: "auto",
    titleRu: "Магнитный держатель телефона",
    titleKz: "Телефонға арналған магнитті ұстағыш",
    description: "Крепление на панель, MagSafe-совместимый корпус.",
    tone: "holder",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 9900,
    groupPrice: 5900,
    cargoCost: 500,
    finalPrice: 6400,
    discount: 35,
    participants: 46,
    target: 50,
    countdown: "00:20:49",
    recommendation: "авто · Алматы · дешево закрыть",
    savingsAmount: 3500,
  }),
  deal({
    id: "dash-cam",
    category: "auto",
    titleRu: "Видеорегистратор 4K",
    titleKz: "4K бейнетіркегіш",
    description: "Передняя камера, ночной режим и запись на парковке.",
    tone: "dashcam",
    city: "Астана",
    source: "Amazon",
    retailPrice: 56900,
    groupPrice: 37900,
    cargoCost: 2200,
    finalPrice: 40100,
    discount: 30,
    participants: 17,
    target: 20,
    countdown: "06:46:00",
    recommendation: "авто · Астана · надежность",
    savingsAmount: 16800,
  }),
  deal({
    id: "travel-jacket",
    category: "fashion",
    titleRu: "Легкая городская куртка",
    titleKz: "Жеңіл қалалық күрте",
    description: "Минималистичная куртка для весны и прохладных вечеров.",
    tone: "jacket",
    city: "Алматы",
    source: "Amazon",
    retailPrice: 89900,
    groupPrice: 62900,
    cargoCost: 3100,
    finalPrice: 66000,
    discount: 27,
    participants: 12,
    target: 20,
    countdown: "09:22:41",
    recommendation: "одежда · Алматы · новый тир",
    savingsAmount: 23900,
  }),
  deal({
    id: "summer-shirt",
    category: "fashion",
    titleRu: "Летняя хлопковая рубашка",
    titleKz: "Жазғы мақта жейде",
    description: "Легкая рубашка свободного кроя.",
    tone: "shirt",
    city: "Алматы",
    source: "1688",
    retailPrice: 32900,
    groupPrice: 21900,
    cargoCost: 1700,
    finalPrice: 23600,
    discount: 28,
    participants: 15,
    target: 20,
    countdown: "05:57:29",
    recommendation: "одежда · Алматы · отпуск",
    savingsAmount: 9300,
  }),
  deal({
    id: "city-sneakers",
    category: "fashion",
    titleRu: "Городские кроссовки",
    titleKz: "Қалалық кроссовкалар",
    description: "Пара для ежедневной ходьбы и летних поездок.",
    tone: "sneakers",
    city: "Астана",
    source: "Amazon",
    retailPrice: 73900,
    groupPrice: 51900,
    cargoCost: 2800,
    finalPrice: 54700,
    discount: 26,
    participants: 8,
    target: 20,
    countdown: "13:32:05",
    recommendation: "одежда · Астана · group price",
    savingsAmount: 19200,
  }),
  deal({
    id: "summer-cap",
    category: "fashion",
    titleRu: "Хлопковая кепка",
    titleKz: "Мақта кепка",
    description: "Базовая кепка с плотной посадкой.",
    tone: "cap",
    city: "Алматы",
    source: "Temu mock",
    retailPrice: 14900,
    groupPrice: 8900,
    cargoCost: 800,
    finalPrice: 9700,
    discount: 35,
    participants: 41,
    target: 50,
    countdown: "01:49:33",
    recommendation: "одежда · Алматы · в бюджете",
    savingsAmount: 5200,
  }),
];

export const featuredDeal = deals[0];

export function getDealById(id: string) {
  return deals.find((item) => item.id === id);
}

export function getDealsByCategory(category?: string) {
  if (!category || category === "all") return deals;
  return deals.filter((item) => item.category === category);
}

export function getDealRails(category?: string, mlRankedDeals?: Deal[]) {
  const scoped = getDealsByCategory(category);
  const rankedScoped = mlRankedDeals && mlRankedDeals.length > 0 ? mlRankedDeals : scoped;
  if (category && category !== "all") {
    return [
      {
        heading: `${categoryLabels[category as DealCategory] ?? "Категория"} · сделки`,
        ctaLabel: "Все сделки",
        ctaHref: "/#deals",
        products: rankedScoped,
      },
      {
        heading: "Почти собрались",
        ctaLabel: "Вступить",
        ctaHref: "#deal-detail",
        products: [...scoped].sort((a, b) => b.participants / b.target - a.participants / a.target).slice(0, 4),
      },
    ];
  }

  return [
    {
      heading: "Рекомендовано вам",
      ctaLabel: "Все сделки",
      ctaHref: "#deals",
      products:
        mlRankedDeals && mlRankedDeals.length > 0
          ? mlRankedDeals.slice(0, 8)
          : [...deals].sort((a, b) => b.recommendationSignals.score - a.recommendationSignals.score).slice(0, 8),
    },
    {
      heading: "Горячие сделки",
      ctaLabel: "Смотреть",
      ctaHref: "#deals",
      products: [...deals].sort((a, b) => b.participants / b.target - a.participants / a.target).slice(0, 8),
    },
    {
      heading: "В вашем городе",
      ctaLabel: "Алматы",
      ctaHref: "#deals",
      products: deals.filter((item) => item.city === "Алматы").slice(0, 8),
    },
    {
      heading: "Почти собрались",
      ctaLabel: "Вступить",
      ctaHref: "#deal-detail",
      products: deals.filter((item) => item.target - item.participants <= 6).slice(0, 8),
    },
  ];
}

export const hero = {
  title: "Соберите группу. Разблокируйте оптовую цену.",
  body:
    "Birge показывает товары с мировых маркетплейсов в тенге, собирает покупателей в группы и снижает цену при достижении оптового количества. SIM ID защищает каждый слот в группе.",
  ctaLabel: "Начать сценарий",
  ctaHref: "/onboarding",
  secondaryCtaLabel: "Смотреть live demo",
  secondaryCtaHref: "/deal/demo",
  image: "/images/cms/2026-06-08-mw-webapp-nh-summer-events-vacation-multibrand-multicategory-img.jpeg",
};

export const stats = [
  { value: "2 412 700 ₸", label: "сэкономлено вместе" },
  { value: "38", label: "групп закрыто" },
  { value: "14", label: "ботов заблокировано" },
  { value: "1 SIM = 1 место", label: "доверенный слот" },
];

export const profile: Profile = {
  name: "Айгерим С.",
  city: "Алматы",
  interests: ["электроника", "дом", "красота", "гаджеты", "кухня"],
  budgetBand: "10 000–50 000 ₸",
  trustScore: 94,
  simVerified: true,
  activeDeals: 4,
  closedDeals: 8,
  savedMoney: 36400,
};
