// Real content extracted from farfetch.com/kz/shopping/men/items.aspx (2026-06-11)
// Generated by scripts/gen-content.mjs — regenerate rather than hand-editing bulk data.
import type {
  HeroContent,
  ProductRailContent,
  SplitBannerContent,
  TrendingContent,
  BrandsMomentContent,
  NavItem,
  FooterColumn,
  HelpBarItem,
} from "@/types/farfetch";

export const bannerMessages: { text: string; href: string }[] = [
  {
    "text": "Enjoy up to 60% off sale, plus 20% off",
    "href": "/promotions/men/summer-promotion"
  },
  {
    "text": "Download the app to get 10% off your first app order",
    "href": "/promotion-terms-and-conditions/"
  },
  {
    "text": "Shop the SS26 sale : up to 60% off",
    "href": "/shopping/men/sale/all/items.aspx"
  }
];

export const genderTabs: { label: string; href: string; active: boolean }[] = [
  {
    "label": "Womenswear",
    "href": "/kz/shopping/women/items.aspx",
    "active": false
  },
  {
    "label": "Menswear",
    "href": "/kz/shopping/men/items.aspx",
    "active": true
  },
  {
    "label": "Kidswear",
    "href": "/kz/shopping/kids/items.aspx",
    "active": false
  }
];

export const navItems: NavItem[] = [
  {
    "label": "Sale",
    "href": "/kz/shopping/men/sale/all/items.aspx",
    "highlight": true,
    "menu": {
      "columns": [
        {
          "heading": "20% off sale",
          "links": [
            {
              "label": "All 20% off",
              "href": "/kz/promotions/men/summer-promotion"
            },
            {
              "label": "20% off clothing",
              "href": "/kz/promotions/men/summer-promotion?&category=136330"
            },
            {
              "label": "20% off sweaters",
              "href": "/kz/promotions/men/summer-promotion?&category=136334"
            },
            {
              "label": "20% off jackets",
              "href": "/kz/promotions/men/summer-promotion?&category=136335"
            },
            {
              "label": "20% off T-shirts",
              "href": "/kz/promotions/men/summer-promotion?&category=136332"
            },
            {
              "label": "20% off shoes",
              "href": "/kz/promotions/men/summer-promotion?&category=135968"
            },
            {
              "label": "20% off trainers",
              "href": "/kz/promotions/men/summer-promotion?&category=137174"
            },
            {
              "label": "20% off bags",
              "href": "/kz/promotions/men/summer-promotion?&category=135970"
            },
            {
              "label": "20% off accessories",
              "href": "/kz/promotions/men/summer-promotion?&category=135972"
            }
          ]
        },
        {
          "heading": "Sale",
          "links": [
            {
              "label": "All sale",
              "href": "/kz/shopping/men/sale/all/items.aspx"
            },
            {
              "label": "Clothing",
              "href": "/kz/shopping/men/sale/clothing-2/items.aspx"
            },
            {
              "label": "Jackets",
              "href": "/kz/shopping/men/sale/jackets-2/items.aspx"
            },
            {
              "label": "Shirts",
              "href": "/kz/shopping/men/sale/shirts-2/items.aspx"
            },
            {
              "label": "Sweatshirts & knitwear",
              "href": "/kz/shopping/men/sale/sweaters-knitwear-2/items.aspx"
            },
            {
              "label": "T-shirts",
              "href": "/kz/shopping/men/sale/t-shirts-vests-2/items.aspx"
            },
            {
              "label": "Shoes",
              "href": "/kz/shopping/men/sale/shoes-2/items.aspx"
            },
            {
              "label": "Trainers",
              "href": "/kz/shopping/men/sale/trainers-2/items.aspx"
            },
            {
              "label": "Bags",
              "href": "/kz/shopping/men/sale/bags-purses-2/items.aspx"
            },
            {
              "label": "Accessories",
              "href": "/kz/shopping/men/sale/accessories-all-2/items.aspx"
            },
            {
              "label": "Previous Season",
              "href": "/kz/shopping/men/sale/all/items.aspx?labels=16900"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "",
        "image": "/images/meganav/wwmw-sale-60-x20.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "New in",
    "href": "/kz/sets/new-in-this-week-eu-men.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "What's New",
          "links": [
            {
              "label": "New in today",
              "href": "/kz/sets/new-in-this-week-eu-men.aspx"
            },
            {
              "label": "New clothing",
              "href": "/kz/sets/men-new-in-clothing.aspx"
            },
            {
              "label": "New shoes",
              "href": "/kz/sets/men-new-in-shoes.aspx"
            },
            {
              "label": "New bags & accessories",
              "href": "/kz/sets/men-new-in-accessories.aspx"
            }
          ]
        },
        {
          "heading": "Trending Now",
          "links": [
            {
              "label": "Retro sportswear",
              "href": "/kz/sets/trend-edit-four.aspx"
            },
            {
              "label": "How to style stripes",
              "href": "/kz/sets/men/stripes-for-men.aspx"
            },
            {
              "label": "The new boho",
              "href": "/kz/sets/men/boho-chic-for-him.aspx"
            },
            {
              "label": "Event-dressing",
              "href": "/kz/sets/men/wedding-guest-mens.aspx"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "Most-wanted pieces",
              "href": "/kz/sets/most-wanted-pieces.aspx"
            },
            {
              "label": "Partywear",
              "href": "/kz/sets/event-dressing-men.aspx"
            },
            {
              "label": "The vacation edit",
              "href": "/kz/sets/vacation-men.aspx"
            },
            {
              "label": "Hype streetwear",
              "href": "/kz/sets/men/street-wear-men.aspx"
            },
            {
              "label": "Exclusives & collabs",
              "href": "/kz/sets/exclusives-collaborations-men.aspx"
            },
            {
              "label": "Best of the new season",
              "href": "/kz/sets/new-season-men.aspx"
            },
            {
              "label": "Fashion feed",
              "href": "/kz/stories/fashion-feed"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "MOST-WANTED PIECES",
        "image": "/images/meganav/mw-08-06-most-wanted.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Vacation",
    "href": "/kz/sets/vacation-men.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Vacation",
          "links": [
            {
              "label": "The vacation edit",
              "href": "/kz/sets/vacation-men.aspx"
            },
            {
              "label": "Swimwear & beachwear",
              "href": "/kz/sets/men/summer-swimwear.aspx"
            },
            {
              "label": "Matching sets",
              "href": "/kz/sets/men/new-season.aspx"
            },
            {
              "label": "Linen staples",
              "href": "/kz/sets/mw-linen.aspx"
            },
            {
              "label": "The summer shirt edit",
              "href": "/kz/sets/men/trend-shirt-edit.aspx"
            },
            {
              "label": "Vacation nights",
              "href": "/kz/sets/event-dressing-men.aspx"
            },
            {
              "label": "How to style shorts",
              "href": "/kz/sets/men/how-to-style-shorts-for-men.aspx"
            },
            {
              "label": "Airport staples",
              "href": "/kz/sets/men/airport-essentials.aspx"
            }
          ]
        },
        {
          "heading": "Accessories",
          "links": [
            {
              "label": "Vacation accessories",
              "href": "/kz/sets/men-vacation-accessories.aspx"
            },
            {
              "label": "Summer shoes",
              "href": "/kz/sets/men/step-into-summer-men.aspx"
            },
            {
              "label": "New sunglasses",
              "href": "/kz/shopping/men/sunglasses-2/items.aspx"
            },
            {
              "label": "Luggage & holdalls",
              "href": "/kz/shopping/men/luggage-holdalls-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Brands",
          "links": [
            {
              "label": "Versace",
              "href": "/kz/shopping/men/versace/items.aspx"
            },
            {
              "label": "Casablanca",
              "href": "/kz/shopping/men/casablanca/items.aspx"
            },
            {
              "label": "Jacquemus",
              "href": "/kz/shopping/men/jacquemus/items.aspx"
            },
            {
              "label": "Orlebar Brown",
              "href": "/kz/shopping/men/orlebar-brown/items.aspx"
            },
            {
              "label": "MC2 Saint Barth",
              "href": "/kz/shopping/men/designer-mc2-saint-barth/items.aspx"
            },
            {
              "label": "Frescobol Carioca",
              "href": "/kz/shopping/men/frescobol-carioca/items.aspx"
            },
            {
              "label": "Vilebrequin",
              "href": "/kz/shopping/men/vilebrequin/items.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "EVENT DRESSING",
        "image": "/images/meganav/mw-08-06-event-dressing.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Brands",
    "href": "/kz/designers/men",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Iconic Brands",
          "links": [
            {
              "label": "View All",
              "href": "/kz/designers/men"
            },
            {
              "label": "Amiri",
              "href": "/kz/shopping/men/amiri/items.aspx"
            },
            {
              "label": "Brunello Cucinelli",
              "href": "/kz/shopping/men/brunello-cucinelli/items.aspx"
            },
            {
              "label": "Burberry",
              "href": "/kz/shopping/men/burberry/items.aspx"
            },
            {
              "label": "Dolce & Gabbana",
              "href": "/kz/shopping/men/dolce-gabbana/items.aspx"
            },
            {
              "label": "Maison Margiela",
              "href": "/kz/shopping/men/maison-margiela/items.aspx"
            },
            {
              "label": "Moncler",
              "href": "/kz/shopping/men/moncler/items.aspx"
            },
            {
              "label": "Off-White",
              "href": "/kz/shopping/men/off-white/items.aspx"
            },
            {
              "label": "Polo Ralph Lauren",
              "href": "/kz/shopping/men/polo-ralph-lauren/items.aspx"
            },
            {
              "label": "Prada",
              "href": "/kz/shopping/men/prada/items.aspx"
            },
            {
              "label": "Tom Ford",
              "href": "/kz/shopping/men/tom-ford/items.aspx"
            }
          ]
        },
        {
          "heading": "Contemporary brands",
          "links": [
            {
              "label": "Carhartt WIP",
              "href": "/kz/shopping/men/carhartt-wip/items.aspx"
            },
            {
              "label": "Chrome Hearts",
              "href": "/kz/shopping/men/chrome-hearts/items.aspx"
            },
            {
              "label": "Fear of God essentials",
              "href": "/kz/shopping/men/essentials/items.aspx"
            },
            {
              "label": "Lemaire",
              "href": "/kz/shopping/men/lemaire/items.aspx"
            },
            {
              "label": "Our Legacy",
              "href": "/kz/shopping/men/our-legacy/items.aspx"
            },
            {
              "label": "Stone island",
              "href": "/kz/shopping/men/stone-island/items.aspx"
            },
            {
              "label": "Represent",
              "href": "/kz/shopping/men/represent/items.aspx"
            },
            {
              "label": "Rhude",
              "href": "/kz/shopping/men/rhude/items.aspx"
            },
            {
              "label": "Visvim",
              "href": "/kz/shopping/men/visvim/items.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "CASABLANCA",
        "image": "/images/meganav/mw-08-06-casablanca.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Clothing",
    "href": "/kz/shopping/men/clothing-2/items.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Clothing",
          "links": [
            {
              "label": "All clothing",
              "href": "/kz/shopping/men/clothing-2/items.aspx"
            },
            {
              "label": "T-shirts & vests",
              "href": "/kz/shopping/men/t-shirts-vests-2/items.aspx"
            },
            {
              "label": "Jackets",
              "href": "/kz/shopping/men/jackets-2/items.aspx"
            },
            {
              "label": "Sweaters & knitwear",
              "href": "/kz/shopping/men/sweaters-knitwear-2/items.aspx"
            },
            {
              "label": "Shirts",
              "href": "/kz/shopping/men/shirts-2/items.aspx"
            },
            {
              "label": "Polo shirts",
              "href": "/kz/shopping/men/polo-shirts-2/items.aspx"
            },
            {
              "label": "Denim",
              "href": "/kz/shopping/men/denim-2/items.aspx"
            },
            {
              "label": "Trousers",
              "href": "/kz/shopping/men/trousers-2/items.aspx"
            },
            {
              "label": "Swimwear & beachwear",
              "href": "/kz/shopping/men/beachwear-2/items.aspx"
            },
            {
              "label": "Shorts",
              "href": "/kz/shopping/men/shorts-2/items.aspx"
            },
            {
              "label": "Coats",
              "href": "/kz/shopping/men/coats-2/items.aspx"
            },
            {
              "label": "Suits",
              "href": "/kz/shopping/men/suits-2/items.aspx"
            },
            {
              "label": "Underwear & socks",
              "href": "/kz/shopping/men/underwear-socks-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "New clothing",
              "href": "/kz/sets/men-new-in-clothing.aspx"
            },
            {
              "label": "Retro sportswear",
              "href": "/kz/sets/trend-edit-four.aspx"
            },
            {
              "label": "Partywear",
              "href": "/kz/sets/event-dressing-men.aspx"
            },
            {
              "label": "The vacation edit",
              "href": "/kz/sets/vacation-men.aspx"
            },
            {
              "label": "Hype streetwear",
              "href": "/kz/sets/men/street-wear-men.aspx"
            },
            {
              "label": "How to style stripes",
              "href": "/kz/sets/men/stripes-for-men.aspx"
            },
            {
              "label": "New-season co-ords",
              "href": "/kz/sets/men/new-season.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "HOW TO STYLE SHORTS",
        "image": "/images/meganav/mw-26-05-how-to-style-shorts.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Shoes",
    "href": "/kz/shopping/men/shoes-2/items.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Shoes",
          "links": [
            {
              "label": "All shoes",
              "href": "/kz/shopping/men/shoes-2/items.aspx"
            },
            {
              "label": "Trainers",
              "href": "/kz/shopping/men/trainers-2/items.aspx"
            },
            {
              "label": "Boots",
              "href": "/kz/shopping/men/boots-2/items.aspx"
            },
            {
              "label": "Loafers",
              "href": "/kz/shopping/men/loafers-2/items.aspx"
            },
            {
              "label": "Derby & Oxford shoes",
              "href": "/kz/shopping/men/derby-oxford-shoes-2/items.aspx"
            },
            {
              "label": "Slippers",
              "href": "/kz/shopping/men/shoes-2/items.aspx?category=135996"
            },
            {
              "label": "Flip flops & Slides",
              "href": "/kz/shopping/men/flip-flops-slides-2/items.aspx"
            },
            {
              "label": "Sandals",
              "href": "/kz/shopping/men/sandals-2/items.aspx"
            },
            {
              "label": "Monk shoes",
              "href": "/kz/shopping/men/buckled-shoes-2/items.aspx"
            },
            {
              "label": "Mules",
              "href": "/kz/shopping/men/shoes-2/items.aspx?category=198967"
            },
            {
              "label": "Espadrilles",
              "href": "/kz/shopping/men/espadrilles-2/items.aspx"
            },
            {
              "label": "Boat shoes",
              "href": "/kz/shopping/men/shoes-2/items.aspx?category=136355"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "New shoes",
              "href": "/kz/sets/men-new-in-shoes.aspx"
            },
            {
              "label": "Most wanted trainers",
              "href": "/kz/sets/men/most-wanted-sneakers.aspx"
            },
            {
              "label": "Party shoes",
              "href": "/kz/sets/men/party-shoes-mens.aspx"
            },
            {
              "label": "Exclusives & collabs",
              "href": "/kz/sets/men/sneakers-exclusives-and-collaborations.aspx"
            },
            {
              "label": "Summer shoes",
              "href": "/kz/sets/men/step-into-summer-men.aspx"
            }
          ]
        },
        {
          "heading": "Iconic Collections",
          "links": [
            {
              "label": "Zegna Triple Stitch",
              "href": "/kz/sets/mw-iconic-sneakers-zegna-triple-stitch.aspx"
            },
            {
              "label": "New Balance 9060",
              "href": "/kz/sets/new-balance-9060.aspx"
            },
            {
              "label": "Maison Margiela Replica",
              "href": "/kz/sets/maison-margiela-replica-trainers.aspx"
            },
            {
              "label": "Golden Goose Ball Star",
              "href": "/kz/sets/golden-goose-ball-star-for-men.aspx"
            },
            {
              "label": "On Cloudtilt",
              "href": "/kz/sets/on-cloudtilt.aspx"
            },
            {
              "label": "Salomon XT-6",
              "href": "/kz/sets/salomon-xt-6.aspx"
            },
            {
              "label": "Jordan x Travis Scott",
              "href": "/kz/sets/nike-x-travis-scott.aspx?sort=2"
            },
            {
              "label": "Maison Mihara Yasuhiro Peterson",
              "href": "/kz/sets/maison-mihara-yasuhiro-peterson.aspx"
            },
            {
              "label": "Rick Owens vintage",
              "href": "/kz/sets/rick-owens-vintage.aspx"
            },
            {
              "label": "adidas x Bad Bunny",
              "href": "/kz/sets/bad-bunny-x-adidas.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "SUMMER SHOES",
        "image": "/images/meganav/mw-02-06-summer-shoes.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Bags",
    "href": "/kz/shopping/men/bags-purses-2/items.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Bags",
          "links": [
            {
              "label": "All bags",
              "href": "/kz/shopping/men/bags-purses-2/items.aspx"
            },
            {
              "label": "Shoulder bags",
              "href": "/kz/shopping/men/shoulder-bags-2/items.aspx"
            },
            {
              "label": "Backpacks",
              "href": "/kz/shopping/men/backpacks-2/items.aspx"
            },
            {
              "label": "Messenger bags",
              "href": "/kz/shopping/men/messengers-2/items.aspx"
            },
            {
              "label": "Tote bags",
              "href": "/kz/shopping/men/totes-2/items.aspx"
            },
            {
              "label": "Luggage & holdalls",
              "href": "/kz/shopping/men/luggage-holdalls-2/items.aspx"
            },
            {
              "label": "Clutch bags",
              "href": "/kz/shopping/men/clutches-2/items.aspx"
            },
            {
              "label": "Belt bags",
              "href": "/kz/shopping/men/belt-bags-2/items.aspx"
            },
            {
              "label": "Laptop bags & briefcases",
              "href": "/kz/shopping/men/laptop-briefcases-2/items.aspx"
            },
            {
              "label": "Beach bags",
              "href": "/kz/shopping/women/bags-purses-1/items.aspx?category=136297"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "New bags & accessories",
              "href": "/kz/sets/men-new-in-accessories.aspx"
            },
            {
              "label": "Pre-owned bags",
              "href": "/kz/shopping/men/pre-owned-bags-2/items.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "BACKPACKS",
        "image": "/images/meganav/mw-08-06-backpacks.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Accessories",
    "href": "/kz/shopping/men/accessories-all-2/items.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Accessories",
          "links": [
            {
              "label": "All accessories",
              "href": "/kz/shopping/men/accessories-all-2/items.aspx"
            },
            {
              "label": "Sunglasses",
              "href": "/kz/shopping/men/sunglasses-2/items.aspx"
            },
            {
              "label": "Hats",
              "href": "/kz/shopping/men/hats-2/items.aspx"
            },
            {
              "label": "Belts",
              "href": "/kz/shopping/men/belts-2/items.aspx"
            },
            {
              "label": "Wallets & cardholders",
              "href": "/kz/shopping/men/wallets-cardholders-2/items.aspx"
            },
            {
              "label": "Glasses & frames",
              "href": "/kz/shopping/men/accessories-all-2/items.aspx?category=136371"
            },
            {
              "label": "Scarves",
              "href": "/kz/shopping/men/scarves-2/items.aspx"
            },
            {
              "label": "Ties & bow ties",
              "href": "/kz/shopping/men/ties-2/items.aspx"
            },
            {
              "label": "Keyrings & chains",
              "href": "/kz/shopping/men/accessories-all-2/items.aspx?category=136010"
            },
            {
              "label": "Gloves",
              "href": "/kz/shopping/men/gloves-2/items.aspx"
            },
            {
              "label": "Phone, computer & gadgets",
              "href": "/kz/shopping/men/accessories-all-2/items.aspx?category=136377"
            },
            {
              "label": "Cufflinks",
              "href": "/kz/shopping/men/accessories-all-2/items.aspx?category=136483"
            }
          ]
        },
        {
          "heading": "Jewellery",
          "links": [
            {
              "label": "All jewellery",
              "href": "/kz/shopping/men/jewellery-2/items.aspx"
            },
            {
              "label": "All fine jewellery",
              "href": "/kz/shopping/men/jewellery-2/items.aspx?view=180&category=136639%7C136635%7C136636%7C136638"
            },
            {
              "label": "Bracelets",
              "href": "/kz/shopping/men/bracelets-2/items.aspx"
            },
            {
              "label": "Necklaces",
              "href": "/kz/shopping/men/necklaces-2/items.aspx"
            },
            {
              "label": "Rings",
              "href": "/kz/shopping/men/rings-2/items.aspx"
            },
            {
              "label": "Earrings",
              "href": "/kz/shopping/men/earrings-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "New accessories & bags",
              "href": "/kz/sets/men-new-in-accessories.aspx"
            },
            {
              "label": "Gifts",
              "href": "/kz/sets/men/menswear-gift-list.aspx"
            },
            {
              "label": "Vacation accessories",
              "href": "/kz/sets/men-vacation-accessories.aspx"
            },
            {
              "label": "Pre-owned accessories",
              "href": "/kz/shopping/men/pre-owned-accessories-2/items.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "SUNGLASSES",
        "image": "/images/meganav/mw-02-06-sunglasses.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Watches",
    "href": "/kz/shopping/men/watches-4/items.aspx",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Watches",
          "links": [
            {
              "label": "All watches",
              "href": "/kz/shopping/men/watches-4/items.aspx"
            },
            {
              "label": "New in watches",
              "href": "/kz/sets/new-in-watches-for-men.aspx"
            },
            {
              "label": "Contemporary watches",
              "href": "/kz/shopping/men/contemporary-watches-2/items.aspx"
            },
            {
              "label": "Fashion watches",
              "href": "/kz/shopping/men/watches-analog-2/items.aspx"
            },
            {
              "label": "Watches accessories",
              "href": "/kz/shopping/men/watch-accessories-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Fine Watches",
          "links": [
            {
              "label": "All fine watches",
              "href": "/kz/shopping/men/fine-watches-4/items.aspx"
            },
            {
              "label": "Aviator watches",
              "href": "/kz/shopping/men/fine-watches-aviator-2/items.aspx"
            },
            {
              "label": "Chronograph watches",
              "href": "/kz/shopping/men/fine-watches-chronograph-2/items.aspx"
            },
            {
              "label": "Dress watches",
              "href": "/kz/shopping/men/fine-watches-dress-2/items.aspx"
            },
            {
              "label": "Sports watches",
              "href": "/kz/shopping/men/fine-watches-sports-2/items.aspx"
            },
            {
              "label": "Pre-owned fine watches",
              "href": "/kz/shopping/men/pre-owned-fine-watches-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Featured Brands",
          "links": [
            {
              "label": "Audemars Piguet",
              "href": "/kz/shopping/men/audemars-piguet/items.aspx"
            },
            {
              "label": "Bell & Ross",
              "href": "/kz/shopping/men/bell-ross/fine-watches-4/items.aspx"
            },
            {
              "label": "Breitling",
              "href": "/kz/shopping/men/breitling/items.aspx"
            },
            {
              "label": "Chopard",
              "href": "/kz/shopping/men/chopard/items.aspx"
            },
            {
              "label": "Designa Individual",
              "href": "/kz/shopping/men/designer-designa-individual/items.aspx"
            },
            {
              "label": "Frederique Constant",
              "href": "/kz/shopping/men/frederique-constant/items.aspx"
            },
            {
              "label": "Hublot",
              "href": "/kz/shopping/men/hublot/items.aspx"
            },
            {
              "label": "Omega",
              "href": "/kz/shopping/men/designer-omega-pre-owned/items.aspx"
            },
            {
              "label": "Patek Philippe",
              "href": "/kz/shopping/men/patek-philippe/items.aspx"
            },
            {
              "label": "Rolex",
              "href": "/kz/shopping/men/rolex-pre-owned/items.aspx"
            },
            {
              "label": "Tag-Heuer",
              "href": "/kz/shopping/men/designer-tag-heuer/items.aspx"
            },
            {
              "label": "Tudor",
              "href": "/kz/shopping/men/tudor/items.aspx"
            }
          ]
        },
        {
          "heading": "Discover",
          "links": [
            {
              "label": "Customised watches",
              "href": "/kz/sets/men/most-wanted-watches.aspx"
            },
            {
              "label": "Pre-order watches",
              "href": "/kz/tag/men/pre-order?view=90&rootCategory=Men&category=137177"
            },
            {
              "label": "Collectors' timepieces",
              "href": "/kz/sets/men/trend-watches-investment-pieces.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "NEW WATCHES",
        "image": "/images/meganav/mw-08-06-watches-1-.jpeg",
        "href": "#"
      }
    }
  },
  {
    "label": "Lifestyle",
    "href": "#",
    "highlight": false,
    "menu": {
      "columns": [
        {
          "heading": "Homeware",
          "links": [
            {
              "label": "All homeware",
              "href": "/kz/shopping/men/lifestyle-2/items.aspx"
            },
            {
              "label": "New homeware",
              "href": "/kz/sets/new-homeware.aspx"
            },
            {
              "label": "Home decor",
              "href": "/kz/shopping/men/home-decor-2/items.aspx"
            },
            {
              "label": "Soft furnishings & textiles",
              "href": "/kz/shopping/men/soft-furninshing-textiles-2/items.aspx"
            },
            {
              "label": "Dining & kitchen",
              "href": "/kz/shopping/men/dining-kitchen-2/items.aspx"
            },
            {
              "label": "Candles & home fragrance",
              "href": "/kz/shopping/men/candles-home-fragrance-2/items.aspx"
            },
            {
              "label": "Stationery",
              "href": "/kz/shopping/men/stationery-2/items.aspx"
            },
            {
              "label": "Collectibles",
              "href": "/kz/shopping/men/collectibles-2/items.aspx"
            },
            {
              "label": "Furniture",
              "href": "/kz/shopping/men/furniture-2/items.aspx"
            },
            {
              "label": "Audio & tech accessories",
              "href": "/kz/shopping/men/audio-tech-accessories-2/items.aspx"
            },
            {
              "label": "Pet accessories",
              "href": "/kz/shopping/men/pet-accessories-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Sports",
          "links": [
            {
              "label": "All activewear",
              "href": "/kz/shopping/men/activewear-2/items.aspx"
            },
            {
              "label": "Skiwear",
              "href": "/kz/shopping/men/skiwear-2/items.aspx"
            },
            {
              "label": "Shoes",
              "href": "/kz/shopping/men/performance-footwear-2/items.aspx"
            },
            {
              "label": "Jackets",
              "href": "/kz/shopping/men/performance-jackets-2/items.aspx"
            },
            {
              "label": "Trousers",
              "href": "/kz/shopping/men/sport-trousers-2/items.aspx"
            },
            {
              "label": "Shorts",
              "href": "/kz/shopping/men/performance-shorts-2/items.aspx"
            },
            {
              "label": "Accessories",
              "href": "/kz/shopping/men/activewear-accessories-2/items.aspx"
            },
            {
              "label": "Tops",
              "href": "/kz/shopping/men/sport-tops-2/items.aspx"
            }
          ]
        },
        {
          "heading": "Travel",
          "links": [
            {
              "label": "Airport staples",
              "href": "/kz/sets/men/airport-essentials.aspx"
            },
            {
              "label": "Luggage & holdalls",
              "href": "/kz/shopping/men/luggage-holdalls-2/items.aspx"
            },
            {
              "label": "Travel accessories",
              "href": "/kz/shopping/men/travel-2/items.aspx"
            },
            {
              "label": "The vacation edit",
              "href": "/kz/sets/vacation-men.aspx"
            }
          ]
        }
      ],
      "spotlight": {
        "label": "NEW HOMEWARE",
        "image": "/images/meganav/mw-26-05-new-homeware.jpeg",
        "href": "#"
      }
    }
  }
];

export const hero: HeroContent = {
  "title": "Whatever the occasion",
  "body": "For summer weddings, garden parties and everything in-between, decode the dress code with AMI Paris, Tom Ford and more",
  "ctaLabel": "Shop Now",
  "ctaHref": "/sets/men/wedding-guest-mens.aspx",
  "image": "/images/cms/2026-06-08-mw-webapp-nh-summer-events-vacation-multibrand-multicategory-img.jpeg"
};

export const newInRail: ProductRailContent = {
  "heading": "New in: handpicked daily from the world’s best brands and boutiques",
  "ctaLabel": "Shop Now",
  "ctaHref": "/kz/sets/new-in-this-week-eu-men.aspx",
  "products": [
    {
      "id": "36281346",
      "badge": "New Season",
      "brand": "Versace",
      "description": "striped cotton-jersey T-shirt",
      "priceFinal": "$847",
      "image": "/images/products/36281346_68487648_600.jpg",
      "image480": "/images/products/36281346_68487648_480.jpg",
      "href": "/kz/shopping/men/versace-striped-cotton-jersey-t-shirt-item-36281346.aspx"
    },
    {
      "id": "34076877",
      "badge": "New Season",
      "brand": "Givenchy",
      "description": "tapered baggy jeans",
      "priceFinal": "$1,323",
      "image": "/images/products/34076877_68955679_600.jpg",
      "image480": "/images/products/34076877_68955679_480.jpg",
      "href": "/kz/shopping/men/givenchy-tapered-baggy-jeans-item-34076877.aspx"
    },
    {
      "id": "36746000",
      "badge": "New Season",
      "brand": "Kenzo",
      "description": "logo-embroidered baseball cap",
      "priceFinal": "$139",
      "image": "/images/products/36746000_68904702_600.jpg",
      "image480": "/images/products/36746000_68904702_480.jpg",
      "href": "/kz/shopping/men/kenzo-logo-embroidered-baseball-cap-item-36746000.aspx"
    },
    {
      "id": "33791811",
      "badge": "New Season",
      "brand": "NN07",
      "description": "Ben check-pattern shirt",
      "priceFinal": "$214",
      "image": "/images/products/33791811_68950015_600.jpg",
      "image480": "/images/products/33791811_68950015_480.jpg",
      "href": "/kz/shopping/men/nn07-ben-check-pattern-shirt-item-33791811.aspx"
    }
  ]
};

export const saleRail: ProductRailContent = {
  "heading": "20% off sale items",
  "ctaLabel": "Shop Now",
  "ctaHref": "/kz/promotions/men/summer-promotion",
  "products": [
    {
      "id": "29510356",
      "badge": "Special Offer",
      "brand": "Jacob Cohën",
      "description": "denim jacket",
      "priceOriginal": "$723",
      "priceFinal": "$549",
      "discountLabel": "-20%",
      "image": "/images/products/29510356_58551338_600.jpg",
      "image480": "/images/products/29510356_58551338_480.jpg",
      "href": "/kz/shopping/men/jacob-cohen-denim-jacket-item-29510356.aspx"
    },
    {
      "id": "34026009",
      "badge": "Special Offer",
      "brand": "A.P.C.",
      "description": "buckled backpack",
      "priceOriginal": "$397",
      "priceIntermediate": "$344",
      "priceFinal": "$275",
      "discountLabel": "-10% -20%",
      "image": "/images/products/34026009_65166053_600.jpg",
      "image480": "/images/products/34026009_65166053_480.jpg",
      "href": "/kz/shopping/men/apc-buckled-backpack-item-34026009.aspx"
    },
    {
      "id": "32462898",
      "badge": "Special Offer",
      "brand": "Philipp Plein",
      "description": "logo T-shirt",
      "priceOriginal": "$421",
      "priceIntermediate": "$252",
      "priceFinal": "$202",
      "discountLabel": "-40% -20%",
      "image": "/images/products/32462898_65689799_600.jpg",
      "image480": "/images/products/32462898_65689799_480.jpg",
      "href": "/kz/shopping/men/philipp-plein-logo-t-shirt-item-32462898.aspx"
    },
    {
      "id": "34766194",
      "badge": "Special Offer",
      "brand": "Paul Smith",
      "description": "floral shirt",
      "priceOriginal": "$279",
      "priceIntermediate": "$251",
      "priceFinal": "$201",
      "discountLabel": "-10% -20%",
      "image": "/images/products/34766194_66105996_600.jpg",
      "image480": "/images/products/34766194_66105996_480.jpg",
      "href": "/kz/shopping/men/paul-smith-floral-shirt-item-34766194.aspx"
    }
  ]
};

export const splitBanner1: SplitBannerContent = {
  "tiles": [
    {
      "title": "Brunello Cucinelli",
      "href": "/kz/shopping/men/brunello-cucinelli/items.aspx",
      "image": "/images/ads/ad-slot-0.png",
      "variant": "overlay"
    },
    {
      "title": "Dolce&Gabbana",
      "href": "/kz/shopping/men/dolce-gabbana/items.aspx",
      "image": "/images/ads/ad-slot-1.png",
      "variant": "overlay"
    }
  ]
} as SplitBannerContent;

export const splitBanner2: SplitBannerContent = {
  "tiles": [
    {
      "title": "Ralph Lauren Purple Label",
      "href": "/kz/shopping/men/ralph-lauren-purple-label/items.aspx",
      "image": "/images/ads/ad-slot-2.png",
      "variant": "overlay"
    },
    {
      "title": "Jimmy Choo",
      "href": "/kz/shopping/men/jimmy-choo/items.aspx",
      "image": "/images/ads/ad-slot-3.png",
      "variant": "overlay"
    }
  ]
} as SplitBannerContent;

export const trending: TrendingContent = {
  "heading": "Trending now",
  "tiles": [
    {
      "title": "SPOTLIGHT ON CASABLANCA",
      "href": "/kz/shopping/men/casablanca/items.aspx",
      "image": "/images/cms/2026-05-25-mw-webapp-casablanca-vacation-casablanca-multicategory-img.jpeg",
      "variant": "caption"
    },
    {
      "title": "THE JACKET UPDATE",
      "href": "/kz/shopping/men/jackets-2/items.aspx",
      "image": "/images/cms/2026-05-25-mw-webapp-jackets-vacation-multibrand-jackets-img.jpeg",
      "variant": "caption"
    },
    {
      "title": "AIRPORT STAPLES",
      "href": "/kz/sets/men/airport-essentials.aspx",
      "image": "/images/cms/2026-05-25-mw-webapp-luggage-holdalls-vacation-multibrand-multicategory-img.jpeg",
      "variant": "caption"
    },
    {
      "title": "HOW TO STYLE SHORTS",
      "href": "/kz/sets/men/how-to-style-shorts-for-men.aspx",
      "image": "/images/cms/2026-05-25-mw-webapp-shorts-vacation-multibrand-shorts-img.jpeg",
      "variant": "caption"
    }
  ]
} as TrendingContent;

export const brands: BrandsMomentContent = {
  "heading": "Brands of the moment",
  "tiles": [
    {
      "title": "Lardini",
      "href": "/kz/shopping/men/lardini/items.aspx",
      "image": "/images/cms/2026-06-01-mw-webapp-lardini-vacation-lardini-multicategory-img.jpeg",
      "variant": "overlay"
    },
    {
      "title": "Boggi Milano",
      "href": "/kz/shopping/men/designer-boggi-milano/items.aspx",
      "image": "/images/cms/2026-06-01-mw-webapp-boggi-milano-vacation-boggi-milano-multicategory-img.jpeg",
      "variant": "overlay"
    },
    {
      "title": "Manière De Voir",
      "href": "/kz/shopping/men/designer-maniere-de-voir/items.aspx",
      "image": "/images/cms/2026-06-01-mw-webapp-maniere-de-voir-vacation-maniere-de-voir-multicategory-img.jpeg",
      "variant": "overlay"
    }
  ]
} as BrandsMomentContent;

export const helpBar: HelpBarItem[] = [
  {
    "icon": "hanger",
    "title": "HOW TO SHOP",
    "body": "Your guide to shopping and placing orders",
    "href": "/kz/how-to-shop"
  },
  {
    "icon": "question",
    "title": "FAQS",
    "body": "Your questions answered",
    "href": "/kz/faqs"
  },
  {
    "icon": "bubble",
    "title": "NEED HELP?",
    "body": "Contact our global Customer Service team",
    "href": "/kz/contact-us"
  }
];

export const newsletter = {
  "heading": "Never miss a thing",
  "body": "Sign up for promotions, tailored new arrivals, stock updates and more – straight to your inbox",
  "updatesLabel": "GET UPDATES BY",
  "methodLabel": "Email",
  "placeholder": "Your email address",
  "buttonLabel": "Sign Up",
  "legal": "By signing up, you consent to receiving marketing by email and/or SMS and acknowledge you have read our Privacy Policy. Unsubscribe anytime at the bottom of our emails or by replying STOP to any of our SMS.",
  "privacyHref": "/kz/privacy-policy/"
};

export const footer: {
  paymentHeading: string;
  columns: FooterColumn[];
  followHeading: string;
  social: { label: string; href: string }[];
  legalLinks: { label: string; href: string }[];
  trademark: string;
  copyright: string;
} = {
  "paymentHeading": "Payment methods",
  "columns": [
    {
      "heading": "Customer Service",
      "links": [
        {
          "label": "Contact us",
          "href": "/kz/contact-us/"
        },
        {
          "label": "FAQs",
          "href": "/kz/faqs/"
        },
        {
          "label": "Orders and delivery",
          "href": "/kz/orders-and-shipping/"
        },
        {
          "label": "Returns and refunds",
          "href": "/kz/returns-and-refunds/"
        },
        {
          "label": "Payment and pricing",
          "href": "/kz/payment-and-pricing/"
        },
        {
          "label": "Cryptocurrency payments",
          "href": "/kz/cryptocurrency-payment"
        },
        {
          "label": "Promotion terms and conditions",
          "href": "/kz/promotion-terms-and-conditions"
        },
        {
          "label": "How to shop",
          "href": "/kz/how-to-shop"
        },
        {
          "label": "FARFETCH Customer Promise",
          "href": "/kz/customer-promise/"
        }
      ]
    },
    {
      "heading": "About FARFETCH",
      "links": [
        {
          "label": "About us",
          "href": "https://aboutfarfetch.com/"
        },
        {
          "label": "FARFETCH partner boutiques",
          "href": "/kz/boutiques"
        },
        {
          "label": "Careers",
          "href": "https://aboutfarfetch.com/careers/our-approach-to-hiring/"
        },
        {
          "label": "FARFETCH app",
          "href": "/kz/discover-app/"
        },
        {
          "label": "Modern slavery statement",
          "href": "/kz/modern-slavery-statement/"
        },
        {
          "label": "FARFETCH Advertising",
          "href": "https://advertising.farfetch.com/#hero"
        },
        {
          "label": "Sitemap",
          "href": "/kz/stories/all-brands-on-sale"
        }
      ]
    },
    {
      "heading": "Discounts and membership",
      "links": [
        {
          "label": "Affiliate program",
          "href": "/kz/pag1987.aspx"
        },
        {
          "label": "Refer a friend",
          "href": "/kz/refer-a-friend?situation=homepage_footer"
        },
        {
          "label": "FARFETCH membership",
          "href": "/kz/farfetch-access-programme"
        },
        {
          "label": "Student Beans and Graduates",
          "href": "/kz/student-discount/student-beans"
        }
      ]
    },
    {
      "heading": "Content and services",
      "links": [
        {
          "label": "Fashion Feed: the latest style stories",
          "href": "/kz/stories/fashion-feed"
        }
      ]
    }
  ],
  "followHeading": "Follow us",
  "social": [
    {
      "label": "instagram",
      "href": "https://instagram.com/farfetch"
    },
    {
      "label": "tikTok",
      "href": "https://www.tiktok.com/@farfetch"
    },
    {
      "label": "facebook",
      "href": "https://www.facebook.com/Farfetch/"
    },
    {
      "label": "youtube",
      "href": "https://www.youtube.com/user/farfetchdotcom"
    }
  ],
  "legalLinks": [
    {
      "label": "Privacy policy",
      "href": "/kz/privacy-policy/"
    },
    {
      "label": "Terms and conditions",
      "href": "/kz/terms-and-conditions/"
    },
    {
      "label": "Accessibility",
      "href": "/kz/farfetch-accessibility/"
    }
  ],
  "trademark": "'FARFETCH' and the 'FARFETCH' logo are trade marks of FARFETCH UK Limited and are registered in numerous jurisdictions around the world.",
  "copyright": "© Copyright 2026 FARFETCH UK Limited. All rights reserved."
};

export const promoModal = {
  "title": "Enjoy 20% off on sale items",
  "body": "For a limited time: enjoy up to 60% off, plus 20% off selected styles",
  "image": "/images/products/CI_d0c99a14-b59b-4326-b109-75779df4cda3_600.jpg",
  "dismissLabel": "Dismiss",
  "ctaLabel": "Shop now",
  "ctaHref": "/kz/shopping/men/sale/all/items.aspx"
};
