import fs from "node:fs";

const symbols = JSON.parse(fs.readFileSync("docs/research/farfetch/svg-symbols-full.json", "utf8"));
const sprites = JSON.parse(fs.readFileSync("docs/research/farfetch/svg-sprites.json", "utf8"));

const nameMap = {
  farfetchMonogram: "FarfetchMonogram",
  "iconLoaded-loader": "LoaderIcon",
  "iconLoaded-chevronDownSmall": "ChevronDownSmallIcon",
  "iconLoaded-user": "UserIcon",
  "iconLoaded-heart": "HeartIcon",
  "iconLoaded-bag": "BagIcon",
  "iconLoaded-tick": "TickIcon",
  "iconLoaded-tickCircle": "TickCircleIcon",
  "iconLoaded-fastDelivery": "FastDeliveryIcon",
  "iconLoaded-magnifier": "MagnifierIcon",
  "iconLoaded-cross": "CrossIcon",
  "iconLoaded-heartFill": "HeartFillIcon",
  "iconLoaded-bubble": "BubbleIcon",
  "iconLoaded-hanger": "HangerIcon",
  "iconLoaded-questionMarkCircle": "QuestionMarkCircleIcon",
  "iconLoaded-kz": "KzFlagIcon",
  "iconLoaded-instagram": "InstagramIcon",
  "iconLoaded-tikTok": "TikTokIcon",
  "iconLoaded-youtube": "YoutubeIcon",
  "iconLoaded-facebook": "FacebookIcon",
  "iconLoaded-fixed-ratio_americanExpress": "AmexLogo",
  "iconLoaded-fixed-ratio_mastercard": "MastercardLogo",
  "iconLoaded-fixed-ratio_visa": "VisaLogo",
  "iconLoaded-fixed-ratio_paypalSecondary": "PaypalLogo",
};

function toJsx(html) {
  return html
    .replace(/<symbol[^>]*>/, "")
    .replace(/<\/symbol>$/, "")
    // nested <svg> inside symbol: strip outer nested svg wrapper if present, keep children
    .replace(/xmlns="[^"]*"/g, "")
    .replace(/xmlns:xlink="[^"]*"/g, "")
    .replace(/xlink:href/g, "href")
    .replace(/class="[^"]*"/g, "")
    .replace(/(\w+)-(\w+)=/g, (m, a, b) => {
      const attr = `${a}-${b}`;
      const keep = ["aria-hidden", "aria-label", "data-testid", "stroke-dasharray"];
      if (keep.includes(attr)) return m;
      return `${a}${b[0].toUpperCase()}${b.slice(1)}=`;
    })
    .replace(/clipPath=/g, "clipPath=")
    .replace(/\s+>/g, ">")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function extractViewBox(html, fallback = "0 0 24 24") {
  const m = html.match(/viewBox="([^"]+)"/);
  return m ? m[1] : fallback;
}

let out = `// Extracted SVG icons from farfetch.com sprite sheet (2026-06-11)
// Generated by scripts/gen-icons.mjs — do not edit by hand.
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;
`;

const seen = new Set();
for (const sym of symbols) {
  const name = nameMap[sym.id];
  if (!name || seen.has(name)) continue;
  seen.add(name);
  const vb = extractViewBox(sym.html);
  let inner = toJsx(sym.html);
  // if symbol wrapped an inner <svg>, unwrap it
  const innerSvg = inner.match(/^<svg[^>]*>([\s\S]*)<\/svg>$/);
  if (innerSvg) inner = innerSvg[1].trim();
  out += `
export function ${name}(props: IconProps) {
  return (
    <svg viewBox="${vb}" fill="currentColor" aria-hidden="true" {...props}>
      ${inner}
    </svg>
  );
}
`;
}

// FARFETCH wordmark logo (inline svg, not a symbol)
const logo = sprites.inline.find((s) => s.html.includes("ff-logo-global"));
if (logo) {
  const vb = extractViewBox(logo.html, "0 0 340.19 42.24");
  let inner = logo.html
    .replace(/<svg[^>]*>/, "")
    .replace(/<\/svg>$/, "")
    .replace(/xmlns="[^"]*"/g, "")
    .replace(/class="[^"]*"/g, "")
    .replace(/(\w+)-(\w+)=/g, (m, a, b) => {
      if (["aria-hidden", "data-testid"].includes(`${a}-${b}`)) return m;
      return `${a}${b[0].toUpperCase()}${b.slice(1)}=`;
    })
    .replace(/\s{2,}/g, " ")
    .trim();
  out += `
export function FarfetchLogo(props: IconProps) {
  return (
    <svg viewBox="${vb}" fill="currentColor" aria-hidden="true" {...props}>
      ${inner}
    </svg>
  );
}
`;
}

fs.writeFileSync("src/components/icons.tsx", out);
console.log("ICONS_DONE components=" + (seen.size + (logo ? 1 : 0)));
